QT.quick_private.VERSION = 5.2.2
QT.quick_private.MAJOR_VERSION = 5
QT.quick_private.MINOR_VERSION = 2
QT.quick_private.PATCH_VERSION = 2
QT.quick_private.name = QtQuick
QT.quick_private.libs = $$QT_MODULE_LIB_BASE
QT.quick_private.includes = $$QT_MODULE_INCLUDE_BASE/QtQuick/5.2.2 $$QT_MODULE_INCLUDE_BASE/QtQuick/5.2.2/QtQuick
QT.quick_private.depends = quick
QT.quick_private.module_config = internal_module no_link
