QT.qmltest_private.VERSION = 5.2.2
QT.qmltest_private.MAJOR_VERSION = 5
QT.qmltest_private.MINOR_VERSION = 2
QT.qmltest_private.PATCH_VERSION = 2
QT.qmltest_private.name = QtQuickTest
QT.qmltest_private.libs = $$QT_MODULE_LIB_BASE
QT.qmltest_private.includes = $$QT_MODULE_INCLUDE_BASE/QtQuickTest/5.2.2 $$QT_MODULE_INCLUDE_BASE/QtQuickTest/5.2.2/QtQuickTest
QT.qmltest_private.depends = qmltest
QT.qmltest_private.module_config = internal_module no_link
