QT.opengl_private.VERSION = 5.2.2
QT.opengl_private.MAJOR_VERSION = 5
QT.opengl_private.MINOR_VERSION = 2
QT.opengl_private.PATCH_VERSION = 2
QT.opengl_private.name = QtOpenGL
QT.opengl_private.libs = $$QT_MODULE_LIB_BASE
QT.opengl_private.includes = $$QT_MODULE_INCLUDE_BASE/QtOpenGL/5.2.2 $$QT_MODULE_INCLUDE_BASE/QtOpenGL/5.2.2/QtOpenGL
QT.opengl_private.depends = opengl
QT.opengl_private.module_config = internal_module no_link
